import {
  X, MapPin, Users, Briefcase, Heart, School, Building2, TreePine, Droplets,
  ArrowUpRight, Star, Calendar, Newspaper, GraduationCap, TrendingUp,
  Leaf, Camera, Phone, Mail, Globe, ChevronLeft, ChevronRight,
  Wind, Zap, Mountain, Waves, Filter, Clock, ExternalLink,
} from "lucide-react";

const STATE_DATA: Record<string, any> = {
  "Maharashtra": {
    tagline: "The Land of Opportunities — Powering India's Future",
    capital: "Mumbai",
    population: "128M",
    area: "307,713 km²",
    literacy: "82.9%",
    languages: "Marathi, Hindi, English",
    climate: "Tropical & Semi-arid",
    heroImg: "https://images.unsplash.com/photo-1710582999228-bf5a133c4573?w=1800&h=900&fit=crop&auto=format",
    stats: [
      { key: "projects", label: "Projects", value: 2847, icon: Briefcase, color: "#4a7cf8", bg: "rgba(74,124,248,0.12)" },
      { key: "beneficiaries", label: "Beneficiaries", value: 1240000, label2: "1.24M", icon: Heart, color: "#ec4899", bg: "rgba(236,72,153,0.12)" },
      { key: "volunteers", label: "Volunteers", value: 84300, label2: "84.3K", icon: Users, color: "#22c55e", bg: "rgba(34,197,94,0.12)" },
      { key: "districts", label: "Districts", value: 36, icon: MapPin, color: "#ff7c3a", bg: "rgba(255,124,58,0.12)" },
      { key: "ngos", label: "NGOs", value: 3120, icon: Building2, color: "#a855f7", bg: "rgba(168,85,247,0.12)" },
      { key: "schools", label: "Schools", value: 110000, label2: "110K", icon: School, color: "#14b8a6", bg: "rgba(20,184,166,0.12)" },
      { key: "hospitals", label: "Hospitals", value: 18500, label2: "18.5K", icon: Building2, color: "#f59e0b", bg: "rgba(245,158,11,0.12)" },
      { key: "trees", label: "Trees Planted", value: 9200000, label2: "9.2M", icon: TreePine, color: "#22c55e", bg: "rgba(34,197,94,0.12)" },
      { key: "water", label: "Water Bodies", value: 342, icon: Droplets, color: "#06b6d4", bg: "rgba(6,182,212,0.12)" },
    ],
    cities: [
      { name: "Mumbai", pop: "20.6M", famous: "Financial capital, Bollywood, Gateway of India", img: "https://images.unsplash.com/photo-1662737897280-226e47d4db8e?w=600&h=400&fit=crop&auto=format" },
      { name: "Pune", pop: "7.4M", famous: "IT hub, education, Shaniwar Wada", img: "https://images.unsplash.com/photo-1732022648903-737e66c18b08?w=600&h=400&fit=crop&auto=format" },
      { name: "Nagpur", pop: "2.9M", famous: "Orange city, zero mile, zero milestone", img: "https://images.unsplash.com/photo-1648115124749-b5d0c3ced1fa?w=600&h=400&fit=crop&auto=format" },
      { name: "Nashik", pop: "1.5M", famous: "Wine capital, Kumbh Mela, grapes", img: "https://images.unsplash.com/photo-1626419825300-c56f471b94a2?w=600&h=400&fit=crop&auto=format" },
    ],
    tourism: [
      { name: "Gateway of India", type: "Monument", rating: 4.8, season: "Oct–Mar", img: "https://images.unsplash.com/photo-1670165184224-85d9145f614f?w=500&h=350&fit=crop&auto=format", location: "Mumbai", desc: "Iconic arch monument overlooking the Arabian Sea, built in 1924." },
      { name: "Ajanta Caves", type: "UNESCO Site", rating: 4.9, season: "Nov–Feb", img: "https://images.unsplash.com/photo-1704788564069-d54cab4169aa?w=500&h=350&fit=crop&auto=format", location: "Aurangabad", desc: "Rock-cut Buddhist cave monuments with exquisite paintings from 2nd century BCE." },
      { name: "Lonar Crater Lake", type: "Nature", rating: 4.6, season: "Dec–Mar", img: "https://images.unsplash.com/photo-1648831180276-2dc08f3db3ef?w=500&h=350&fit=crop&auto=format", location: "Buldhana", desc: "Rare saltwater crater lake formed by a meteorite impact 50,000 years ago." },
      { name: "Mahabaleshwar", type: "Hill Station", rating: 4.7, season: "Mar–Jun", img: "https://images.unsplash.com/photo-1648115124749-b5d0c3ced1fa?w=500&h=350&fit=crop&auto=format", location: "Satara", desc: "Scenic hill station with strawberry farms, valleys, and panoramic viewpoints." },
      { name: "Ellora Caves", type: "UNESCO Site", rating: 4.9, season: "Nov–Mar", img: "https://images.unsplash.com/photo-1670509628897-333df68d1d90?w=500&h=350&fit=crop&auto=format", location: "Aurangabad", desc: "Hindu, Buddhist, and Jain monuments cut from basalt cliff, 6th–11th century." },
      { name: "Tadoba Tiger Reserve", type: "Wildlife", rating: 4.7, season: "Apr–Jun", img: "https://images.unsplash.com/photo-1626419825300-c56f471b94a2?w=500&h=350&fit=crop&auto=format", location: "Chandrapur", desc: "Maharashtra's oldest national park with highest tiger density in India." },
    ],
    culture: [
      { title: "Lavani Dance", cat: "Dance", img: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=400&h=300&fit=crop&auto=format", desc: "Traditional Maharashtrian folk dance performed with dholki rhythm." },
      { title: "Puran Poli", cat: "Cuisine", img: "https://images.unsplash.com/photo-1567016376408-0226e4d0c1ea?w=400&h=300&fit=crop&auto=format", desc: "Sweet flatbread stuffed with chana dal and jaggery — a festive staple." },
      { title: "Ganesh Chaturthi", cat: "Festival", img: "https://images.unsplash.com/photo-1662737897280-226e47d4db8e?w=400&h=300&fit=crop&auto=format", desc: "India's grandest ten-day festival honoring Lord Ganesha." },
      { title: "Paithani Saree", cat: "Clothing", img: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=400&h=300&fit=crop&auto=format", desc: "Handwoven silk saree with zari border — a UNESCO intangible heritage craft." },
    ],
    economy: {
      gdp: "₹36.4 Trillion",
      gdpGrowth: "8.2%",
      sectors: [
        { name: "Services", value: 58 },
        { name: "Industry", value: 26 },
        { name: "Agriculture", value: 16 },
      ],
      industries: [
        { name: "IT & Tech", value: 85, color: "#4a7cf8" },
        { name: "Manufacturing", value: 72, color: "#ff7c3a" },
        { name: "Finance", value: 91, color: "#22c55e" },
        { name: "Agriculture", value: 60, color: "#f59e0b" },
        { name: "Tourism", value: 55, color: "#a855f7" },
      ],
      monthlyGDP: [
        { month: "Jan", value: 2.9 }, { month: "Feb", value: 3.1 }, { month: "Mar", value: 3.4 },
        { month: "Apr", value: 2.8 }, { month: "May", value: 3.0 }, { month: "Jun", value: 3.3 },
        { month: "Jul", value: 2.7 }, { month: "Aug", value: 3.2 }, { month: "Sep", value: 3.5 },
        { month: "Oct", value: 3.8 }, { month: "Nov", value: 3.6 }, { month: "Dec", value: 4.0 },
      ],
    },
    education: [
      { name: "IIT Bombay", type: "IIT", rank: "#1 India", city: "Mumbai" },
      { name: "AIIMS Nagpur", type: "AIIMS", rank: "Premier Medical", city: "Nagpur" },
      { name: "University of Mumbai", type: "University", rank: "Asia Top 500", city: "Mumbai" },
      { name: "COEP Pune", type: "NIT-equivalent", rank: "#3 Maharashtra", city: "Pune" },
      { name: "Symbiosis International", type: "Deemed University", rank: "Top 20 India", city: "Pune" },
      { name: "TISS Mumbai", type: "Research Institute", rank: "#1 Social Sciences", city: "Mumbai" },
    ],
    environment: [
      { label: "Forest Cover", value: 20.1, unit: "% of area", color: "#22c55e" },
      { label: "Air Quality Index", value: 68, unit: "AQI (Moderate)", color: "#f59e0b" },
      { label: "Renewable Energy", value: 42, unit: "% of total", color: "#4a7cf8" },
      { label: "Water Bodies Restored", value: 73, unit: "% target met", color: "#06b6d4" },
    ],
    wildlife: ["Tadoba Tiger Reserve", "Melghat Tiger Reserve", "Navegaon NP", "Pench NP"],
    rivers: ["Godavari", "Krishna", "Tapi", "Narmada", "Wardha"],
    timeline: [
      { year: "2024", title: "₹10T Infrastructure Investment", desc: "Maharashtra announces largest ever infrastructure spend across road, rail, and port networks." },
      { year: "2023", title: "Semiconductor Policy Launched", desc: "State becomes first to offer dedicated semiconductor manufacturing incentives — 3 plants confirmed." },
      { year: "2022", title: "Mumbai Metro Phase 3 Opens", desc: "32 km underground metro connects Colaba to SEEPZ, cutting commute by 45 minutes." },
      { year: "2021", title: "1 Lakh Trees Campaign", desc: "Urban afforestation drive plants 100,000 trees across 15 cities in 90 days." },
      { year: "2020", title: "PM Kisan Expanded Coverage", desc: "Maharashtra enrolls 12.8M farmers, highest state participation nationally." },
    ],
    gallery: [
      { img: "https://images.unsplash.com/photo-1710582999228-bf5a133c4573?w=500&h=600&fit=crop&auto=format", caption: "Mumbai Aerial — Bandra-Worli Sea Link" },
      { img: "https://images.unsplash.com/photo-1662737897280-226e47d4db8e?w=500&h=350&fit=crop&auto=format", caption: "Mumbai City Skyline at Dusk" },
      { img: "https://images.unsplash.com/photo-1704788564069-d54cab4169aa?w=500&h=400&fit=crop&auto=format", caption: "Ajanta Caves — Ancient Sculptures" },
      { img: "https://images.unsplash.com/photo-1670165184224-85d9145f614f?w=500&h=600&fit=crop&auto=format", caption: "Gateway of India — Mumbai Harbour" },
      { img: "https://images.unsplash.com/photo-1626419825300-c56f471b94a2?w=500&h=350&fit=crop&auto=format", caption: "Western Ghats — Monsoon Lush" },
      { img: "https://images.unsplash.com/photo-1648115124749-b5d0c3ced1fa?w=500&h=450&fit=crop&auto=format", caption: "Sahyadri Mountains — Sunset" },
      { img: "https://images.unsplash.com/photo-1648831180276-2dc08f3db3ef?w=500&h=380&fit=crop&auto=format", caption: "Nagpur by Night — Orange City Glow" },
      { img: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=500&h=450&fit=crop&auto=format", caption: "Pune Heritage — Shaniwar Wada Fort" },
    ],
    news: [
      { cat: "Economy", title: "Maharashtra tops FDI inflows for third consecutive year with ₹4.2T investment", source: "Business Standard", time: "2h ago", img: "https://images.unsplash.com/photo-1710582999228-bf5a133c4573?w=200&h=140&fit=crop&auto=format", summary: "The state attracted the highest foreign direct investment in India, driven by semiconductor and EV sectors." },
      { cat: "Tech", title: "Pune AI corridor receives ₹800Cr from Centre for deep tech startups", source: "TechCrunch India", time: "5h ago", img: "https://images.unsplash.com/photo-1693159682618-074078ed271e?w=200&h=140&fit=crop&auto=format", summary: "The funding will establish 5 new AI research labs and accelerate 200 startups over the next 3 years." },
      { cat: "Environment", title: "Mangrove cover in Mumbai expands by 12% — largest recorded growth in a decade", source: "The Hindu", time: "8h ago", img: "https://images.unsplash.com/photo-1626419825300-c56f471b94a2?w=200&h=140&fit=crop&auto=format", summary: "Urban conservation efforts and coastal regulation zone enforcement credited for the milestone." },
      { cat: "Education", title: "IIT Bombay launches India's first quantum computing undergraduate program", source: "India Today", time: "1d ago", img: "https://images.unsplash.com/photo-1713122446901-40884feae0b2?w=200&h=140&fit=crop&auto=format", summary: "The four-year B.Tech program in Quantum Engineering begins in the 2025–26 academic year." },
      { cat: "Sports", title: "Mumbai Indians win IPL 2025 — Rohit Sharma's record sixth title", source: "Cricbuzz", time: "1d ago", img: "https://images.unsplash.com/photo-1662737897280-226e47d4db8e?w=200&h=140&fit=crop&auto=format", summary: "A nail-biting final at Wankhede saw MI chase 186 runs, Bumrah taking 4 wickets in the death overs." },
      { cat: "Health", title: "Maharashtra achieves 100% institutional delivery in 25 districts — WHO lauds milestone", source: "Times of India", time: "2d ago", img: "https://images.unsplash.com/photo-1648115124749-b5d0c3ced1fa?w=200&h=140&fit=crop&auto=format", summary: "ASHA workers and telemedicine network credited for the maternal health breakthrough in tribal districts." },
    ],
    events: [
      { title: "Kala Ghoda Arts Festival", date: "Feb 1–10, 2026", type: "Culture", loc: "Mumbai", desc: "Asia's largest urban arts festival with 500+ events, installations, and performances." },
      { title: "Pune Climate Summit", date: "Mar 15, 2026", type: "Environment", loc: "Pune", desc: "State-wide conference on net-zero roadmap with 80+ NGOs and industry leaders." },
      { title: "Maharashtra Startup Conclave", date: "Apr 8–9, 2026", type: "Tech", loc: "Nagpur", desc: "Annual gathering for 1,200 founders, VCs, and government officials." },
      { title: "Vitthal Rukumai Yatra", date: "Jun 20, 2026", type: "Culture", loc: "Pandharpur", desc: "Annual pilgrimage attracting over 2 million devotees to the sacred banks of Bhima." },
    ],
    contact: {
      office: "Maharashtra State Development Authority, Mantralaya, Mumbai 400032",
      email: "info@maharashtra.gov.in",
      phone: "+91-22-2202-4567",
      website: "https://www.maharashtra.gov.in",
      socials: ["@MahaGovtOfficial", "@MaharashtraTourism", "@StartupMaharashtra"],
    },
  },
  "Tamil Nadu": {
    tagline: "Where Stories Meet Glory — The Land of Culture & Innovation",
    capital: "Chennai",
    population: "76.8M",
    area: "130,060 km²",
    literacy: "80.1%",
    languages: "Tamil, English",
    climate: "Tropical & Coastal Maritime",
    heroImg: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1800&h=900&fit=crop&auto=format",
    stats: [
      { key: "projects", label: "Projects", value: 3125, icon: Briefcase, color: "#4a7cf8", bg: "rgba(74,124,248,0.12)" },
      { key: "beneficiaries", label: "Beneficiaries", value: 1420000, label2: "1.42M", icon: Heart, color: "#ec4899", bg: "rgba(236,72,153,0.12)" },
      { key: "volunteers", label: "Volunteers", value: 96500, label2: "96.5K", icon: Users, color: "#22c55e", bg: "rgba(34,197,94,0.12)" },
      { key: "districts", label: "Districts", value: 38, icon: MapPin, color: "#ff7c3a", bg: "rgba(255,124,58,0.12)" },
      { key: "ngos", label: "NGOs", value: 2840, icon: Building2, color: "#a855f7", bg: "rgba(168,85,247,0.12)" },
      { key: "schools", label: "Schools", value: 58000, label2: "58K", icon: School, color: "#14b8a6", bg: "rgba(20,184,166,0.12)" },
      { key: "hospitals", label: "Hospitals", value: 14200, label2: "14.2K", icon: Building2, color: "#f59e0b", bg: "rgba(245,158,11,0.12)" },
      { key: "trees", label: "Trees Planted", value: 7800000, label2: "7.8M", icon: TreePine, color: "#22c55e", bg: "rgba(34,197,94,0.12)" },
      { key: "water", label: "Water Bodies", value: 412, icon: Droplets, color: "#06b6d4", bg: "rgba(6,182,212,0.12)" },
    ],
    cities: [
      { name: "Chennai", pop: "11.5M", famous: "Detroit of Asia, Marina Beach, Cultural Capital", img: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&h=400&fit=crop&auto=format" },
      { name: "Coimbatore", pop: "3.2M", famous: "Manchester of South India, Textiles, Engineering", img: "https://images.unsplash.com/photo-1623492161474-0f2c42d3c9ba?w=600&h=400&fit=crop&auto=format" },
      { name: "Madurai", pop: "1.8M", famous: "Athens of the East, Meenakshi Amman Temple, Jasmine", img: "https://images.unsplash.com/photo-1601999109332-542b18dbec57?w=600&h=400&fit=crop&auto=format" },
      { name: "Trichy", pop: "1.2M", famous: "Rockfort Temple, educational hub, clean city", img: "https://images.unsplash.com/photo-1600664901390-3413988af3ee?w=600&h=400&fit=crop&auto=format" },
    ],
    tourism: [
      { name: "Shore Temple", type: "UNESCO Site", rating: 4.8, season: "Oct–Mar", img: "https://images.unsplash.com/photo-1580834311002-861c8aef9fcd?w=500&h=350&fit=crop&auto=format", location: "Mahabalipuram", desc: "Structural stone temple overlooking the Bay of Bengal, built in the 8th century AD." },
      { name: "Meenakshi Amman Temple", type: "Monument", rating: 4.9, season: "Nov–Feb", img: "https://images.unsplash.com/photo-1601999109332-542b18dbec57?w=500&h=350&fit=crop&auto=format", location: "Madurai", desc: "Historic Hindu temple famed for its 14 magnificent gopurams and exquisite Dravidian architecture." },
      { name: "Nilgiri Mountain Railway", type: "UNESCO Site", rating: 4.7, season: "Mar–Jun", img: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=500&h=350&fit=crop&auto=format", location: "Ooty", desc: "Historic steam-operated toy train running through dense forests and scenic mountain passes." },
      { name: "Brihadeeswarar Temple", type: "UNESCO Site", rating: 4.9, season: "Oct–Feb", img: "https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=500&h=350&fit=crop&auto=format", location: "Thanjavur", desc: "World's first complete granite temple, built by Emperor Raja Raja Chola I in 1010 AD." },
      { name: "Kanyakumari Sunset Point", type: "Nature", rating: 4.6, season: "Nov–Mar", img: "https://images.unsplash.com/photo-1543306634-60ef09341c30?w=500&h=350&fit=crop&auto=format", location: "Kanyakumari", desc: "The southernmost tip of mainland India, where the Arabian Sea, Bay of Bengal, and Indian Ocean meet." },
      { name: "Mudumalai Tiger Reserve", type: "Wildlife", rating: 4.5, season: "Dec–Apr", img: "https://images.unsplash.com/photo-1615959189197-48a653f3c160?w=500&h=350&fit=crop&auto=format", location: "Nilgiris", desc: "Crucial wildlife corridor connecting the Western and Eastern Ghats, boasting rich avian and tiger populations." },
    ],
    culture: [
      { title: "Bharatanatyam", cat: "Dance", img: "https://images.unsplash.com/photo-1618235472857-e1cbfa288219?w=400&h=300&fit=crop&auto=format", desc: "The oldest classical dance tradition of India, rooted in ancient temple culture." },
      { title: "Idli & Sambar", cat: "Cuisine", img: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400&h=300&fit=crop&auto=format", desc: "Steamed fermented rice cakes served with lentil stew — a globally loved breakfast staple." },
      { title: "Pongal", cat: "Festival", img: "https://images.unsplash.com/photo-1610448721566-47369c768e70?w=400&h=300&fit=crop&auto=format", desc: "A four-day harvest festival celebrating the Sun God and cattle." },
      { title: "Kanchipuram Silk Saree", cat: "Clothing", img: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400&h=300&fit=crop&auto=format", desc: "Magnificent handwoven silk textiles featuring heavy zari work and traditional borders." },
    ],
    economy: {
      gdp: "₹31.5 Trillion",
      gdpGrowth: "8.1%",
      sectors: [
        { name: "Services", value: 53 },
        { name: "Industry", value: 34 },
        { name: "Agriculture", value: 13 },
      ],
      industries: [
        { name: "Automobile", value: 92, color: "#ff7c3a" },
        { name: "IT & SaaS", value: 81, color: "#4a7cf8" },
        { name: "Textiles", value: 88, color: "#f59e0b" },
        { name: "Renewables", value: 85, color: "#22c55e" },
        { name: "Electronics", value: 76, color: "#a855f7" },
      ],
      monthlyGDP: [
        { month: "Jan", value: 2.5 }, { month: "Feb", value: 2.7 }, { month: "Mar", value: 3.0 },
        { month: "Apr", value: 2.4 }, { month: "May", value: 2.6 }, { month: "Jun", value: 2.9 },
        { month: "Jul", value: 2.5 }, { month: "Aug", value: 2.8 }, { month: "Sep", value: 3.1 },
        { month: "Oct", value: 3.3 }, { month: "Nov", value: 3.1 }, { month: "Dec", value: 3.5 },
      ],
    },
    education: [
      { name: "IIT Madras", type: "IIT", rank: "#1 India (NIRF)", city: "Chennai" },
      { name: "NIT Trichy", type: "NIT", rank: "#1 NIT India", city: "Trichy" },
      { name: "Anna University", type: "University", rank: "Top Technical State University", city: "Chennai" },
      { name: "CMC Vellore", type: "Medical College", rank: "#3 Medical India", city: "Vellore" },
      { name: "Amrita Vishwa Vidyapeetham", type: "Deemed University", rank: "Top 10 India", city: "Coimbatore" },
      { name: "Loyola College", type: "Arts & Science", rank: "#4 College India", city: "Chennai" },
    ],
    environment: [
      { label: "Forest Cover", value: 23.8, unit: "% of area", color: "#22c55e" },
      { label: "Air Quality Index", value: 52, unit: "AQI (Good/Moderate)", color: "#22c55e" },
      { label: "Renewable Energy", value: 47, unit: "% of total", color: "#4a7cf8" },
      { label: "Water Bodies Restored", value: 81, unit: "% target met", color: "#06b6d4" },
    ],
    wildlife: ["Mudumalai Tiger Reserve", "Anamalai Tiger Reserve", "Sathyamangalam TR", "Guindy National Park"],
    rivers: ["Kaveri", "Vaidhai", "Thamirabarani", "Palar", "Ponnaiyar"],
    timeline: [
      { year: "2025", title: "Global Investors Meet Success", desc: "Tamil Nadu secures record investment commitments worth ₹6.6 Trillion, generating millions of jobs." },
      { year: "2024", title: "Fintech City Launch", desc: "State inaugurates a premium 56-acre Fintech City hub in Chennai to accelerate banking technology." },
      { year: "2023", title: "Naan Mudhalvan Milestone", desc: "Flagship skill development scheme trains over 1.3 million college youth across the state." },
      { year: "2022", title: "Free Bus Travel for Women", desc: "State implements revolutionary free transit policy, boosting women's workforce participation dramatically." },
      { year: "2021", title: "Makkalai Thedi Maruthuvam", desc: "Inauguration of community-based door-step healthcare program targeting non-communicable diseases." },
    ],
    gallery: [
      { img: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=500&h=600&fit=crop&auto=format", caption: "Chennai Horizon — Central Heritage Station" },
      { img: "https://images.unsplash.com/photo-1601999109332-542b18dbec57?w=500&h=350&fit=crop&auto=format", caption: "Madurai Meenakshi Temple Tower Detail" },
      { img: "https://images.unsplash.com/photo-1580834311002-861c8aef9fcd?w=500&h=400&fit=crop&auto=format", caption: "Mahabalipuram — Ancient Rock Relic" },
      { img: "https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=500&h=600&fit=crop&auto=format", caption: "Thanjavur Brihadeeswarar Vimanam Tower" },
      { img: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=500&h=350&fit=crop&auto=format", caption: "Ooty Hills — Toy Train Track Trackways" },
      { img: "https://images.unsplash.com/photo-1623492161474-0f2c42d3c9ba?w=500&h=450&fit=crop&auto=format", caption: "Western Ghats — Nilgiri Range Mist" },
      { img: "https://images.unsplash.com/photo-1543306634-60ef09341c30?w=500&h=380&fit=crop&auto=format", caption: "Kanyakumari — Thiruvalluvar Statue" },
      { img: "https://images.unsplash.com/photo-1600664901390-3413988af3ee?w=500&h=450&fit=crop&auto=format", caption: "Trichy Heritage — Rockfort Temple Vista" },
    ],
    news: [
      { cat: "Economy", title: "Tamil Nadu retains top spot in electronics exports with record $9.5B milestone", source: "The Hindu", time: "3h ago", img: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=200&h=140&fit=crop&auto=format", summary: "The state leads India's electronic exports, driven heavily by giant smartphone assembly expansions and electronic cluster setups." },
      { cat: "Tech", title: "Hosur EV corridor commands 65% of India's electric two-wheeler production", source: "Economic Times", time: "6h ago", img: "https://images.unsplash.com/photo-1693159682618-074078ed271e?w=200&h=140&fit=crop&auto=format", summary: "Major infrastructure investments turn Hosur into India's undeniable premier Electric Vehicle and clean mobility superpower." },
      { cat: "Environment", title: "Tamil Nadu expands green canopy — state adds 3 new Ramsar wetland sites", source: "Times of India", time: "9h ago", img: "https://images.unsplash.com/photo-1615959189197-48a653f3c160?w=200&h=140&fit=crop&auto=format", summary: "With persistent restoration projects, the state protects critical coastal marsh ecosystems under international conservation frameworks." },
      { cat: "Education", title: "IIT Madras holds historic top ranking in NIRF National Standings for successive years", source: "NDTV Education", time: "1d ago", img: "https://images.unsplash.com/photo-1713122446901-40884feae0b2?w=200&h=140&fit=crop&auto=format", summary: "Pioneering research structures and industry partnerships retain the institute's position as India's premier engineering institute." },
      { cat: "Sports", title: "Chennai Super Kings claim thrilling IPL victory at Chepauk Stadium", source: "ESPN Cricinfo", time: "1d ago", img: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=200&h=140&fit=crop&auto=format", summary: "A spectacular masterclass in death bowling brought the crowds to their feet as the yellow army secured another historic IPL banner." },
      { cat: "Health", title: "State healthcare infrastructure leads in infant survival rate — UNICEF gives high rating", source: "Deccan Chronicle", time: "2d ago", img: "https://images.unsplash.com/photo-1600664901390-3413988af3ee?w=200&h=140&fit=crop&auto=format", summary: "Decentralized neonatal intensive care networks and strict community outreach deliver massive drops in state medical indicators." },
    ],
    events: [
      { title: "Margazhi Music Festival", date: "Dec 15 – Jan 15, 2026", type: "Culture", loc: "Chennai", desc: "The world's largest cultural music event showcasing over 1,000 classical Carnatic and Bharatanatyam performances." },
      { title: "Chennai International Book Fair", date: "Jan 16–18, 2026", type: "Education", loc: "Chennai", desc: "Global literary market venue representing over 40 countries promoting cultural exchanges and translations." },
      { title: "Coimbatore Texfair Conclave", date: "Feb 22–25, 2026", type: "Industry", loc: "Coimbatore", desc: "South India's premier textiles expo showing advanced automated machinery from around the globe." },
      { title: "Chithirai Festival", date: "Apr 28, 2026", type: "Culture", loc: "Madurai", desc: "A magnificent month-long grand reenactment attracting millions of pilgrims to the banks of the Vaigai River." },
    ],
    contact: {
      office: "Tamil Nadu Government Development Authority, Fort St. George, Chennai 600009",
      email: "info@tn.gov.in",
      phone: "+91-44-2567-1234",
      website: "https://www.tn.gov.in",
      socials: ["@tngovtoffice", "@TamilNaduTourism", "@GuidanceTamilNadu"],
    },
  },
};



export default STATE_DATA